---
# - hosts: all
#   remote_user: zak
#   become: yes
#   become_user: root
#   become_method: sudo

- hosts: all # group of targets
  #gather_facts: False # get information of plateform running on - False - cuz it required python (if true get error)
  remote_user: zak
  become: yes
  become_user: root
  become_method: sudo

  tasks: 
    roles:
      - run_test
