---
# - hosts: all
#   remote_user: zak
#   become: yes
#   become_user: root
#   become_method: sudo

- hosts: all # group of targets
  #gather_facts: False # get information of plateform running on - False - cuz it required python (if true get error)
  remote_user: zak
  become: yes
  become_user: root
  become_method: sudo

  tasks: 
    # - name: create docker container {{ item }} 
    #   raw: docker run -dit --name ub{{ item }}  ubuntu /bin/bash
    #   with_sequence: "count=4"

    - name: get docker container {{ item }} ip
      shell: "docker container inspect -f '{''{range .NetworkSettings.Networks}''}''{''{.IPAddress}''}''{''{end}''}' ub{{ item }}"
      register: ip_container
    - copy: 
        content: "{{ ip_container.stdout_lines }}" 
        dest: /home/zak/properties
      with_sequence: "count=4"
      
# - group:
#         name: "group{{ item }}"
#         state: present
#       with_sequence:
#         count: 4
  # roles:
  #   - run_test
# - set_fact:
#     string_to_echo: "{{ command_output.stdout }}"