---
# - hosts: all
#   remote_user: zak
#   become: yes
#   become_user: root
#   become_method: sudo

- hosts: all # group of targets
  #gather_facts: False # get information of plateform running on - False - cuz it required python (if true get error)
  remote_user: zak
  become: yes
  become_user: root
  become_method: sudo

  tasks: 
    # - name: run docker commande
    #   raw: docker run -dit --name ub2 ubuntu /bin/bash

    - name: get docker container ip
      shell: "docker container inspect -f '{''{range .NetworkSettings.Networks}''}''{''{.IPAddress}''}''{''{end}''}' ub2"
      register: ip_container

    - debug:
        msg: "IP :  {{ ip_container.stdout_lines }} "
      

  # roles:
  #   - run_test
# - set_fact:
#     string_to_echo: "{{ command_output.stdout }}"