---

- name: clone script {{Nom_Projet}}
  git:
    repo: git@github.com:{{Git_User}}/{{Nom_Projet}}.git
    dest: /home/zak/Git/{{Nom_Projet}}
    accept_hostkey: true
    clone: yes
    key_file: /home/zak/.ssh/id_rsa
  tags:
    - clone

- include: slaves.yml
  when: "{{ NumServers | version_compare('0.0', '>') }}"

- name: create master container 
  raw: docker run -dit --name master_{{Nom_Projet}} jmeter:client /bin/bash

- name: copy {{Nom_Projet}} to master container
  raw: docker cp /home/zak/Git/{{Nom_Projet}}/ master_{{Nom_Projet}}:{{Nom_Projet}}

# - name: copy ProjetSIS to container

# - name: execute script ProjetSIS

# - name: Get result

# - name: destroy container

  

