---
- name: create docker container {{ item }} 
  raw: docker run -dit --name slave_{{ Nom_Projet }}{{ item }}  jmeter:server /bin/bash
  with_sequence: "count={{ NumServers }}"

- name: get slaves ip 
  shell: "docker container inspect -f '{''{range .NetworkSettings.Networks}''}''{''{.IPAddress}''}''{''{end}''}' slave_'{{ Nom_Projet }}''{{ item }}'"
  with_sequence: "count={{ NumServers }}"
  register: ip_container

- name: save to properties file 
  copy: 
    content: "{{ ip_container.results | map(attribute='stdout') | list }}"
    dest: '/home/zak/properties'

- name: format ip
  raw: sed -i -e 's/"//g' properties && sed -i -e 's/\]//g' properties && sed -i -e 's/\[//g' properties && sed -i -e 's/ //g' properties 

- name: set remote properties
  raw: sed -i '1s/^/remote.host=/' properties

# - name: copy data folder to slaves 
#   raw: docker cp /home/zak/Git/{{Nom_Projet}}/data/ master_{{Nom_Projet}}:data

# - name: write properties
